title: Pinacode Lab
email: pinacodelab@gmail.com
description: PinacodeLab offers solutions for your digital problems. We develop websites and platforms using cutting edge technologies. Our main goal is to deliver value for your business and save you time.
baseurl: ""
url: https://pinacodelab.com
logo: assets/images/logo.png

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - CNAME
  - LICENSE
  - README.md
  - webpack.config.js
  - "*.lock"
  - "*.log"
